In [1]:
import numpy as np

In [2]:
#создание массива
datal = [ [5.2, 3.0, 4.5] , [9.1, 0.1, 0.3]]
arrl = np.array(datal) 
arrl

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [57]:
arrl.ndim 

2

In [5]:
arrl.size

6

In [6]:
arrl.shape

(2, 3)

In [7]:
arrl.dtype

dtype('float64')

In [8]:
arrl.itemsize 

8

---

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [13]:
#единичная матрица
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Операции между массивами и скалярами

In [14]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 

In [15]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [16]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

### Случайные массивы

In [18]:
np.random.randn(3,2)

array([[ 0.72397867,  1.88438912],
       [ 1.05997456, -0.15962203],
       [-0.27415005, -1.09174707]])

In [19]:
np.random.randint(0, 1000, 4)

array([534, 320, 971, 226])

### Индексирование

Схоже с индексированием списков.

In [20]:
np.arange(15)[8:12]

array([ 8,  9, 10, 11])

In [21]:
#многомерные массивы
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [22]:
arr2d[0, 2] 

3

In [23]:
arr2d[0][2] 

3

In [24]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
arr3d[1,1][2]

12

In [25]:
arr3d[:1,:1,1:]

array([[[2, 3]]])

In [26]:
#булевое индексирование
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [27]:
mask = (names == 'Bob') | (names == 'Will') 
mask

array([ True, False,  True,  True,  True, False, False])

In [28]:
names[mask]

array(['Bob', 'Will', 'Bob', 'Will'], dtype='<U4')

### Транспонирование массивов

In [29]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d.shape

(2, 2, 3)

In [31]:
arr3d.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [32]:
arr3d.T.shape

(3, 2, 2)

### Поэлементные операции над массивами

Это векторные обертки вокруг простых функций, которые принимают одно или несколько скалярных значений и порождают один или несколько скалярных результатов.

In [33]:
np.sqrt(arr3d)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ],
        [3.16227766, 3.31662479, 3.46410162]]])

In [34]:
np.exp(arr3d)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]])

### Математические и статистические операции

In [35]:
arr = np.random.randn(5, 4) 
arr

array([[-0.20701037, -0.28822768, -0.00938251,  0.29656778],
       [ 0.84409381, -1.41967387, -0.70615542, -0.34075313],
       [-0.58775617, -0.41988766, -1.52022391, -0.02118706],
       [ 0.32499687,  0.34504735,  1.04123563,  0.86058462],
       [-2.67727837,  0.3371122 ,  0.68495864,  0.34829086]])

In [36]:
arr.shape

(5, 4)

In [37]:
arr.mean()

-0.15573241927191822

In [38]:
arr.sum()

-3.114648385438364

In [39]:
np.max(arr)

1.0412356342448525

In [40]:
arr.sum(axis = 0)

array([-2.30295423, -1.44562967, -0.50956756,  1.14350307])

In [41]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]) 

In [42]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [43]:
arr.cumprod(axis = 0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

### Сортировка

In [44]:
arr = np.random.randn(8) 
arr

array([-0.35287728, -2.12653352, -1.0045183 , -0.02924902, -1.37607627,
       -0.30193783,  0.15221404,  0.38525639])

In [45]:
arr.sort()
arr

array([-2.12653352, -1.37607627, -1.0045183 , -0.35287728, -0.30193783,
       -0.02924902,  0.15221404,  0.38525639])

In [46]:
arr = np.random.randn(5,3) 
arr

array([[-0.04255956,  1.03863664, -0.24585359],
       [ 1.07682383, -0.20343598, -0.74254274],
       [-1.32776691, -0.31763347,  0.42608314],
       [-1.42840349,  0.33377431, -0.08587779],
       [-0.84847874,  0.3183479 ,  0.00189834]])

In [47]:
arr.sort(0)
arr

array([[-1.42840349, -0.31763347, -0.74254274],
       [-1.32776691, -0.20343598, -0.24585359],
       [-0.84847874,  0.3183479 , -0.08587779],
       [-0.04255956,  0.33377431,  0.00189834],
       [ 1.07682383,  1.03863664,  0.42608314]])

In [48]:
arr.sort(1) 
arr

array([[-1.42840349, -0.74254274, -0.31763347],
       [-1.32776691, -0.24585359, -0.20343598],
       [-0.84847874, -0.08587779,  0.3183479 ],
       [-0.04255956,  0.00189834,  0.33377431],
       [ 0.42608314,  1.03863664,  1.07682383]])

In [49]:
#возвращает копию
arr = np.random.randn(5,3) 
np.sort(arr)

array([[-1.08376791, -0.5835392 ,  0.27414281],
       [-0.23165941, -0.0580871 ,  0.98276296],
       [ 0.39892019,  1.05644581,  1.43463317],
       [-0.10420571,  0.46645636,  1.02652177],
       [-0.86194719, -0.20468241,  0.81457926]])

In [50]:
arr = np.sort(arr)
arr

array([[-1.08376791, -0.5835392 ,  0.27414281],
       [-0.23165941, -0.0580871 ,  0.98276296],
       [ 0.39892019,  1.05644581,  1.43463317],
       [-0.10420571,  0.46645636,  1.02652177],
       [-0.86194719, -0.20468241,  0.81457926]])

### Хранение массивов на диске в двоичном формате 

*np.save* и *np.load* - основные функции для эффективного сохранения и загрузки данных с диска. По умолчанию массивы хранятся в несжатом двоичном формате в файле с расширением *.npy*. 

In [51]:
arr = np.arange(10)

In [52]:
np.save('some_array', arr) 

In [53]:
np.load( 'some_array.npy') 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Можно сохранить несколько массивов в ziр-архиве с помощью функции np. savez, которой массивы передаются в виде именованных аргументов: 

In [54]:
np.savez('array_archive.npz', a=arr, b=arr) 

In [55]:
arch = np.load('array_archive.npz') 

In [56]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])